config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  resources :orders do
    resources :order_items
  end

  resources :customers
  
  resources :tipe_products
  resources :products

  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/logout', to: 'login#logout'

  get '/ecomerce/product/:product_id', to: 'ecomerce#show_product'
  get '/ecomerce/cart/:product_id/add', to: 'ecomerce#add'
  get '/ecomerce/cart/:product_id/remove', to: 'ecomerce#remove'
  get '/ecomerce/cart', to: 'ecomerce#cart'
  get '/ecomerce/cart/pay', to: 'ecomerce#pay'
  get '/customer/logar', to: 'ecomerce#login_customer'
  post '/customer/login', to: 'ecomerce#login'
  get '/customer/new', to: 'ecomerce#new'
  post '/customer/create', to: 'ecomerce#create'
  patch '/customer/create', to: 'ecomerce#create'
  get '/customer/logout', to: 'ecomerce#logout'
  

  root to: 'home#index'
end

app/models/tipe_product.rb
class TipeProduct < ApplicationRecord
  has_many :products
end

app/controllers/tipe_products_controller.rb
class TipeProductsController < ApplicationController
  before_action :set_tipe_product, only: [:show, :edit, :update, :destroy]

  # GET /tipe_products
  # GET /tipe_products.json
  def index
    @tipe_products = TipeProduct.all
  end

  # GET /tipe_products/1
  # GET /tipe_products/1.json
  def show
  end

  # GET /tipe_products/new
  def new
    @tipe_product = TipeProduct.new
  end

  # GET /tipe_products/1/edit
  def edit
  end

  # POST /tipe_products
  # POST /tipe_products.json
  def create
    @tipe_product = TipeProduct.new(tipe_product_params)

    respond_to do |format|
      if @tipe_product.save
        format.html { redirect_to @tipe_product, notice: 'Tipe product was successfully created.' }
        format.json { render :show, status: :created, location: @tipe_product }
      else
        format.html { render :new }
        format.json { render json: @tipe_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipe_products/1
  # PATCH/PUT /tipe_products/1.json
  def update
    respond_to do |format|
      if @tipe_product.update(tipe_product_params)
        format.html { redirect_to @tipe_product, notice: 'Tipe product was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipe_product }
      else
        format.html { render :edit }
        format.json { render json: @tipe_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipe_products/1
  # DELETE /tipe_products/1.json
  def destroy
    @tipe_product.destroy
    respond_to do |format|
      format.html { redirect_to tipe_products_url, notice: 'Tipe product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipe_product
      @tipe_product = TipeProduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipe_product_params
      params.require(:tipe_product).permit(:name)
    end
end

app/helpers/tipe_products_helper.rb
module TipeProductsHelper
end

app/views/tipe_products/_form.html.erb
<%= form_for(@tipe_product, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @tipe_product.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@tipe_product.errors.count, "error") %> prohibited this tipe_product from being saved:</h4>

      <ul>
      <% @tipe_product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Salvar', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/tipe_products/edit.html.erb
<div class="page-header">
  <%= link_to tipe_products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @tipe_product, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando tipe_product</h1>
</div>

<%= render 'form' %>

app/views/tipe_products/index.html.erb
<div class="page-header">
  <%= link_to new_tipe_product_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h1>Listando tipe_products</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @tipe_products) do |tipe_product| %>
            <td><%= tipe_product.name %></td>
            <td><%= link_to 'Mostrar', tipe_product %></td>
        <td><%= link_to 'Editar', edit_tipe_product_path(tipe_product) %></td>
        <td><%= link_to 'Deletar', tipe_product, method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tipe_products/new.html.erb
<div class="page-header">
  <%= link_to tipe_products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo tipe_product</h1>
</div>

<%= render 'form' %>

app/views/tipe_products/show.html.erb
<div class="page-header">
  <%= link_to tipe_products_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_tipe_product_path(@tipe_product), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar tipe_product</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @tipe_product.name %></dd>

</dl>