config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  resources :orders do
    resources :order_items
  end

  resources :customers
  
  resources :tipe_products
  resources :products

  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/logout', to: 'login#logout'

  get '/ecomerce/product/:product_id', to: 'ecomerce#show_product'
  get '/ecomerce/cart/:product_id/add', to: 'ecomerce#add'
  get '/ecomerce/cart/:product_id/remove', to: 'ecomerce#remove'
  get '/ecomerce/cart', to: 'ecomerce#cart'
  get '/ecomerce/cart/pay', to: 'ecomerce#pay'
  get '/customer/logar', to: 'ecomerce#login_customer'
  post '/customer/login', to: 'ecomerce#login'
  get '/customer/new', to: 'ecomerce#new'
  post '/customer/create', to: 'ecomerce#create'
  patch '/customer/create', to: 'ecomerce#create'
  get '/customer/logout', to: 'ecomerce#logout'
  

  root to: 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer_id, :total_price)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for(@order, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @order.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h4>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :customer, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :customer_id, Customer.all.collect{|t|
                      [t.name, t.id]},{:prompt => 'Selecione'}, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :total_price, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :total_price, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Salvar', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @order, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando order</h1>
</div>

<%= render 'form' %>

app/views/orders/index.html.erb
<div class="page-header">
  <%= link_to new_order_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h1>Listando orders</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Customer</th>
            <th>Total price</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @orders) do |order| %>
        <td><%= order.customer.name %></td>
        <td><%= order.total_price %></td>
        <td><%= link_to 'Mostrar', order %></td>
        <td><%= link_to 'Itens', order_order_items_path(order) %></td>
        <td><%= link_to 'Editar', edit_order_path(order) %></td>
        <td><%= link_to 'Deletar', order, method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/orders/new.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo order</h1>
</div>

<%= render 'form' %>

app/views/orders/show.html.erb
<div class="page-header">
  <%= link_to orders_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_order_path(@order), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar order</h1>
</div>

<dl class="dl-horizontal">
  <dt>Customer:</dt>
  <dd><%= @order.customer.name %></dd>

  <dt>Total price:</dt>
  <dd><%= @order.total_price %></dd>

</dl>