config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  resources :orders do
    resources :order_items
  end

  resources :customers
  
  resources :tipe_products
  resources :products

  get '/admin', to: 'admin#index'
  get '/login', to: 'login#index'
  post '/login/logar', to: 'login#logar'
  get '/login/logout', to: 'login#logout'

  get '/ecomerce/product/:product_id', to: 'ecomerce#show_product'
  get '/ecomerce/cart/:product_id/add', to: 'ecomerce#add'
  get '/ecomerce/cart/:product_id/remove', to: 'ecomerce#remove'
  get '/ecomerce/cart', to: 'ecomerce#cart'
  get '/ecomerce/cart/pay', to: 'ecomerce#pay'
  get '/customer/logar', to: 'ecomerce#login_customer'
  post '/customer/login', to: 'ecomerce#login'
  get '/customer/new', to: 'ecomerce#new'
  post '/customer/create', to: 'ecomerce#create'
  patch '/customer/create', to: 'ecomerce#create'
  get '/customer/logout', to: 'ecomerce#logout'
  

  root to: 'home#index'
end

app/models/administrator.rb
class Administrator < ApplicationRecord
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:name, :email, :password)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @administrator.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h4>

      <ul>
      <% @administrator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit 'Salvar', class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<div class="page-header">
  <%= link_to administrators_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @administrator, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando administrator</h1>
</div>

<%= render 'form' %>

app/views/administrators/index.html.erb
<div class="page-header">
  <%= link_to new_administrator_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h1>Listando administrators</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Password</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @administrators) do |administrator| %>
            <td><%= administrator.name %></td>
            <td><%= administrator.email %></td>
            <td><%= administrator.password %></td>
            <td><%= link_to 'Mostrar', administrator %></td>
        <td><%= link_to 'Editar', edit_administrator_path(administrator) %></td>
        <td><%= link_to 'Deletar', administrator, method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/administrators/new.html.erb
<div class="page-header">
  <%= link_to administrators_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo administrator</h1>
</div>

<%= render 'form' %>

app/views/administrators/show.html.erb
<div class="page-header">
  <%= link_to administrators_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_administrator_path(@administrator), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar administrator</h1>
</div>

<dl class="dl-horizontal">
  <dt>Name:</dt>
  <dd><%= @administrator.name %></dd>

  <dt>Email:</dt>
  <dd><%= @administrator.email %></dd>

  <dt>Password:</dt>
  <dd><%= @administrator.password %></dd>

</dl>